import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Inter } from 'next/font/google';
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
// УДАЛЕНО: import { notFound } from "next/navigation";

const inter = Inter({
    subsets: ['latin', 'cyrillic'],
    variable: '--font-inter',
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout({ children, params }) {
  // Дожидаемся параметров (обязательно в Next.js 15/16)
  const { locale } = await params;

  // УДАЛЕНО: блок проверки if(!['ru', 'en', 'uz'].includes(locale)) { notFound(); }

  // Просто загружаем сообщения для текущего языка
  const messages = await getMessages();

  return (
    <html 
      lang={locale}
      className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <NextIntlClientProvider messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
